// editor/src/components/workspace/Preview.vue
<template>
  <div ref="wrapper" id="wrapper">
    <canvas
      ref="preview"
      id="preview"
      @mousedown="mouseDown"
      @mouseup="() => (mouse = false)"
      @mouseleave="() => (mouse = false)"
      @mousemove="mouseMove"
      @wheel="scroll"
    ></canvas>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, Ref, watch } from 'vue'
import { useEngineStore } from '../../stores/EngineStore'

const EngineStore = useEngineStore()

const offsetX = ref(0)
const offsetY = ref(0)

const preview: Ref<null | HTMLCanvasElement> = ref(null)
const wrapper: Ref<null | HTMLDivElement> = ref(null)

let mouse = false
let mouseDownX = 0
let mouseDownY = 0

function mouseDown(event: MouseEvent) {
  mouse = true

  mouseDownX = event.clientX
  mouseDownY = event.clientY
}

function mouseMove(event: MouseEvent) {
  if (!mouse) return
  if (!preview.value) return

  offsetX.value += event.clientX - mouseDownX
  offsetY.value += event.clientY - mouseDownY

  mouseDownX = event.clientX
  mouseDownY = event.clientY
}

let zoom = ref(1)

function scroll(event: any) {
  const scrollY = event.deltaY / 30000

  zoom.value = Math.pow(Math.pow(zoom.value, 1 / 10) - scrollY, 10)

  zoom.value = Math.max(zoom.value, 0.0001)
}

const canvasScale = 2

async function renderCanvas() {
  if (!wrapper.value) return
  if (!preview.value) return
  if (!preview) return

  if (!EngineStore.loaded) return

  const render = await EngineStore.render(EngineStore.frame)

  const ctx = preview.value.getContext('2d')!
  ctx.imageSmoothingEnabled = false
  ctx.clearRect(0, 0, preview.value.width, preview.value.height)

  const ratioWidth = preview.value.width
  const ratioHeight = preview.value.height * (16 / 9)

  const bestWidth = Math.min(ratioWidth, ratioHeight)

  const bestHeight = bestWidth * (9 / 16)
  const scaledWidth = bestWidth * zoom.value
  const scaledHeight = bestHeight * zoom.value

  ctx.drawImage(
    render,
    (wrapper.value.offsetWidth * canvasScale) / 2 +
      offsetX.value * canvasScale -
      scaledWidth / 2,
    (wrapper.value.offsetHeight * canvasScale) / 2 +
      offsetY.value * canvasScale -
      scaledHeight / 2,
    scaledWidth,
    scaledHeight
  )
}

watch(offsetX, renderCanvas)

watch(offsetY, renderCanvas)

watch(zoom, renderCanvas)

watch(() => EngineStore.frame, renderCanvas)

watch(() => EngineStore.reloadEngineEvent, renderCanvas)

function fixPreviewSize() {
  if (!wrapper.value) return
  if (!preview.value) return

  preview.value.width = wrapper.value.offsetWidth * canvasScale
  preview.value.height = wrapper.value.offsetHeight * canvasScale
  preview.value.style.maxWidth = wrapper.value.offsetWidth + 'px'
  preview.value.style.maxHeight = wrapper.value.offsetHeight + 'px'

  renderCanvas()
}

onMounted(() => {
  if (!wrapper.value) return

  new ResizeObserver(fixPreviewSize).observe(wrapper.value)

  fixPreviewSize()
})
</script>

<style scoped>
#wrapper {
  background-color: black;

  flex-grow: 1;

  margin: 0;
  padding: 0;

  max-height: 100%;
}

#preview {
  display: block;

  margin: 0;

  position: absolute;

  image-rendering: pixelated;
}
</style>

// editor-new/src/Components/Preview.svelte
<script lang="ts">
	import { subscribe } from 'svelte/internal'
	import { engine, frame } from '../Stores/EngineStore.js'
	import { get } from 'svelte/store'
	import { getBestFittingBounds } from '../Utils/aspectRatio.js'
	import { playFrameRate } from '../Stores/PlayStore.js'

	let canvas: undefined | HTMLCanvasElement = undefined
	let containerWidth = 1920
	let containerHeight = 1080

	let offsetX = 0
	let offsetY = 0
	let scale = 1

	let mouse = false
	let mouseDownX = 0
	let mouseDownY = 0

	function mouseDown(event: MouseEvent) {
		mouse = true

		mouseDownX = event.clientX
		mouseDownY = event.clientY
	}

	function mouseMove(event: MouseEvent) {
		if (!mouse) return

		offsetX += event.clientX - mouseDownX
		offsetY += event.clientY - mouseDownY

		mouseDownX = event.clientX
		mouseDownY = event.clientY
	}

	function mouseUp(event: MouseEvent) {
		mouse = false
	}

	function scroll(event: any) {
		const canvasBounds = canvas.getBoundingClientRect()
		const mouseOffsetX = event.clientX - (canvasBounds.left + canvasBounds.right) / 2
		const mouseOffsetY = event.clientY - (canvasBounds.top + canvasBounds.bottom) / 2
		const scrollY = event.deltaY / -4000

		const zoom = Math.exp(scrollY)

		const width = canvasBounds.right - canvasBounds.left
		const widthDelta = width * zoom - width
		const offsetXFactor = (mouseOffsetX / width) * 2
		offsetX -= (widthDelta / 2) * offsetXFactor

		const height = canvasBounds.top - canvasBounds.bottom
		const heightDelta = height * zoom - height
		const offsetYFactor = (mouseOffsetY / height) * 2
		offsetY -= (heightDelta / 2) * offsetYFactor

		scale *= zoom
	}

	async function render() {
		if (!canvas) return

		const engineValue = get(engine)

		if (engineValue === undefined) return

		const render = await engineValue.render()

		const ctx = canvas.getContext('2d')!
		ctx.imageSmoothingEnabled = false

		ctx.clearRect(0, 0, canvas.width, canvas.height)

		ctx.drawImage(render, 0, 0, canvas.width, canvas.height)
	}

	subscribe(engine, value => {
		render()
	})

	subscribe(frame, () => {
		render()
	})

	$: if (canvas) {
		const size = getBestFittingBounds(containerWidth, containerHeight, 16 / 9)

		canvas.style.maxWidth = size.width + 'px'
		canvas.style.maxHeight = size.height + 'px'
	}

	$: if (canvas) {
		canvas.style.translate = offsetX + 'px' + ' ' + offsetY + 'px'
		canvas.style.scale = scale.toString()
	}
</script>

<main
	bind:clientWidth={containerWidth}
	bind:clientHeight={containerHeight}
	on:mousedown={mouseDown}
	on:mousemove={mouseMove}
	on:mouseleave={mouseUp}
	on:mouseup={mouseUp}
	on:wheel={scroll}
>
	<p>{$playFrameRate}</p>

	<canvas bind:this={canvas} width={1920} height={1080} />
</main>

<style>
	main {
		background: #000000;
		height: 50%;

		display: flex;
		justify-content: center;
		align-items: center;

		overflow: hidden;

		position: relative;
	}

	main > p {
		position: absolute;

		top: 0.5rem;
		left: 0.5rem;

		margin: 0;

		color: var(--text);

		font-size: small;
	}

	canvas {
		background-image: url('../Assets/checker.png');
		background-repeat: repeat;
		background-position: bottom left;
		image-rendering: pixelated;

		display: block;

		width: 100%;
		height: 100%;
	}
</style>
