// packages/editor/src/components/workspace/Timeline.vue
<template>
  <div id="component">
    <div id="control-bar">
      <div class="control-bar-group">
        <input
          id="time-input"
          v-model.lazy="timeInputBuffer"
          @blur="timeInputBuffer = (<any>$event).target.value"
        />
        <input
          id="frame-input"
          v-model.lazy="frameInputBuffer"
          @blur="frameInputBuffer = (<any>$event).target.value"
        />
      </div>

      <div class="control-bar-group">
        <span
          class="material-symbols-outlined icon-button"
          @click="() => (EditorStore.muted = !EditorStore.muted)"
        >
          {{ EditorStore.muted ? 'volume_off' : 'volume_up' }}
        </span>

        <input
          id="speed-input"
          v-model.lazy="speedInputBuffer"
          @blur="speedInputBuffer = (<any>$event).target.value"
        />
      </div>

      <div class="control-bar-group">
        <span
          class="material-symbols-outlined icon-button"
          @click="EditorStore.restart"
        >
          fast_rewind
        </span>

        <span
          class="material-symbols-outlined icon-button"
          @click="EditorStore.back"
        >
          skip_previous
        </span>

        <span
          class="material-symbols-outlined icon-button"
          @click="
            () =>
              EditorStore.playing ? EditorStore.pause() : EditorStore.play()
          "
        >
          {{ EditorStore.playing ? 'pause' : 'play_arrow' }}
        </span>

        <span
          class="material-symbols-outlined icon-button"
          @click="EditorStore.next"
        >
          skip_next
        </span>
      </div>

      <div class="control-bar-group">
        <span
          id="redo"
          class="material-symbols-outlined icon-button"
          :class="{ looping: EditorStore.looping }"
          @click="loop"
        >
          redo
        </span>

        <span
          class="material-symbols-outlined icon-button"
          @click="createMarker"
        >
          add
        </span>

        <span
          class="material-symbols-outlined icon-button"
          @click="deleteMarker"
        >
          delete
        </span>
      </div>

      <div class="control-bar-group">
        <p id="frame-length">{{ EngineStore.length }}</p>
        <p id="length">{{ lengthTime }}</p>
      </div>
    </div>
    <div ref="canvasWrapper" id="canvas-wrapper">
      <canvas
        ref="canvas"
        id="canvas"
        @mousedown="mouseDown"
        @mouseup="mouseUp"
        @mouseleave="mouseUp"
        @mousemove="mouseMove"
        @wheel="scroll"
        @contextmenu.prevent=""
      ></canvas>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, Ref, ref, watch, computed } from 'vue'

import { useEngineStore } from '../../stores/EngineStore'
import { useEditorStore } from '../../stores/EditorStore'

const EngineStore = useEngineStore()
const EditorStore = useEditorStore()

function deleteMarker() {
  if (!EditorStore.selectedMarker) return

  EditorStore.deleteMarker(EditorStore.selectedMarker)
}

// watch(
//   () => WorkspaceStore.muted,
//   muted => {
//     WorkspaceStore.audioGain.gain.value = muted ? 0 : WorkspaceStore.volume
//   }
// )

async function createMarker() {
  EditorStore.createMarker(`Marker`, EngineStore.frame)
}

let audioBufferSource: null | AudioBufferSourceNode = null

async function startAudioPlayback(time: number) {
  // const audioBuffer = WorkspaceStore.getAudioBuffer()
  // if (!audioBuffer) return
  // audioBufferSource = WorkspaceStore.audioContext.createBufferSource()
  // audioBufferSource.buffer = audioBuffer
  // audioBufferSource.connect(WorkspaceStore.audioDestination)
  // WorkspaceStore.audioContext.resume()
  // audioBufferSource.start(0, time)
  // while (WorkspaceStore.audioContext.state == 'suspended') {
  //   await new Promise<void>(res => {
  //     setTimeout(() => {
  //       res()
  //     }, 1)
  //   })
  // }
}

function stopAudioPlayback() {
  if (!audioBufferSource) return

  audioBufferSource.stop()
}

const speedInputBuffer = computed({
  get: () => {
    return `${EditorStore.speed}x`
  },
  set: passedSpeed => {
    if (/^(([0-9]*\.[0-9]+)|([0-9]+))x?$/.test(passedSpeed)) {
      const readSpeed = passedSpeed.endsWith('x')
        ? parseFloat(passedSpeed.substring(0, passedSpeed.length - 1))
        : parseFloat(passedSpeed)

      if (readSpeed == 0) {
        const originalSpeed = EditorStore.speed
        EditorStore.speed = -1
        EditorStore.speed = originalSpeed
      } else {
        EditorStore.speed = readSpeed
      }
    } else {
      const originalSpeed = EditorStore.speed
      EditorStore.speed = -1
      EditorStore.speed = originalSpeed
    }
  },
})

const timeInputBuffer = computed({
  get: () => {
    const seconds = EngineStore.frame / EngineStore.frameRate
    const minutes = Math.floor(seconds / EngineStore.frameRate)
    const leftSeconds =
      Math.floor((seconds - minutes * EngineStore.frameRate) * 1000) / 1000
    if (Math.floor(leftSeconds).toString().length == 1)
      return `${minutes}:0${leftSeconds}`
    return `${minutes}:${leftSeconds}`
  },
  set: frame => {
    if (/^(([0-9]+:[0-9]+\.[0-9]{1,3})|([0-9]+:[0-9]+))$/.test(frame)) {
      const minutes = parseInt(frame.split(':')[0])
      const seconds =
        parseFloat(frame.split(':')[1]) + minutes * EngineStore.frameRate
      const frames = Math.floor(seconds * EngineStore.frameRate)
      EngineStore.setFrame(
        Math.max(Math.min(frames, EngineStore.length - 1), 0)
      )
    } else {
      const originalFrame = EngineStore.frame
      EngineStore.frame = -1
      EngineStore.frame = originalFrame
    }
  },
})

const frameInputBuffer = computed({
  get: () => EngineStore.frame,
  set: (frame: any) => {
    if (/^[0-9]+$/.test(frame)) {
      EngineStore.setFrame(
        Math.min(Math.max(parseInt(frame), 0), EngineStore.length - 1)
      )
    } else {
      const originalFrame = EngineStore.frame
      EngineStore.frame = -1
      EngineStore.frame = originalFrame
    }
  },
})

const lengthTime = computed(() => {
  const seconds = EngineStore.length / EngineStore.frameRate
  const minutes = Math.floor(seconds / EngineStore.frameRate)
  const leftSeconds =
    Math.floor((seconds - minutes * EngineStore.frameRate) * 1000) / 1000
  if (Math.floor(leftSeconds).toString().length == 1)
    return `${minutes}:0${leftSeconds}`
  return `${minutes}:${leftSeconds}`
})

const canvasScale = 2

let mouse = false
let mouseAlt = false

let grabbedScrollbar = false
let grabbedScrollbarOffset = 0

let selectedOriginal = ref(0)
let selectedStart = ref(0)
let selectedEnd = ref(0)
let framesSelected = ref(false)

let highlightedMarker: Ref<string | null> = ref(null)
let heldMarker: Ref<string | null> = ref(null)
let heldMarkerX: Ref<number> = ref(0)
let heldMarkerOffset = 0

let holdingPlayhead: boolean = false
let holdingPlayheadFrame: Ref<number> = ref(0)

function frameToRelativeX(frame: number): number {
  if (!canvas.value) return -1

  return Math.floor(
    ((frame - startFrame.value) / (endFrame.value - startFrame.value)) *
      canvas.value.width
  )
}

function XtoFrame(x: number) {
  if (!canvas.value) return -1

  const factor =
    (x * canvasScale - canvas.value.getBoundingClientRect().left) /
    canvas.value.width

  return Math.round(
    factor * (endFrame.value - startFrame.value) + startFrame.value
  )
}

function handleSelectingMarker(event: MouseEvent) {
  if (!canvas.value) return

  const relativeY = event.clientY - canvas.value.getBoundingClientRect().top

  if (relativeY >= 58 && relativeY <= 72) {
    const ctx = canvas.value.getContext('2d')!

    for (const marker of EngineStore.markers) {
      if (event.clientX < frameToRelativeX(marker.frame) / canvasScale) continue

      ctx.font = `10px JetBrainsMono`
      const width = ctx.measureText(marker.name).width + 8

      if (event.clientX > frameToRelativeX(marker.frame) / canvasScale + width)
        continue

      EditorStore.selectedMarker = marker.id

      heldMarker.value = marker.id
      heldMarkerOffset =
        frameToRelativeX(marker.frame) / canvasScale - event.clientX

      highlightedMarker.value = null
    }
  }
}

function handleSelectingScrollbar(event: MouseEvent) {
  if (!canvas.value) return

  if (
    heldMarker.value == null &&
    event.clientY - canvas.value.getBoundingClientRect().top >=
      canvas.value.height / canvasScale - 8
  ) {
    const relativeX = event.clientX - canvas.value.getBoundingClientRect().left

    let scrollBarStart =
      ((canvas.value.width / canvasScale) * startFrame.value) /
      EngineStore.length

    const scrollBarWidth =
      ((canvas.value.width / canvasScale) *
        (endFrame.value - startFrame.value)) /
      EngineStore.length

    if (
      relativeX < scrollBarStart ||
      relativeX > scrollBarStart + scrollBarWidth
    ) {
      const viewRange = endFrame.value - startFrame.value

      const targetFrame =
        (relativeX / (canvas.value.width / canvasScale)) * EngineStore.length

      startFrame.value = targetFrame - viewRange / 2
      endFrame.value = targetFrame + viewRange / 2

      scrollBarStart =
        ((canvas.value.width / canvasScale) * startFrame.value) /
        EngineStore.length
    }

    grabbedScrollbar = true
    grabbedScrollbarOffset = scrollBarStart - relativeX
  }

  if (heldMarker.value == null && !grabbedScrollbar) holdingPlayhead = true
}

function handleSelectingPlayhead(event: MouseEvent) {
  if (heldMarker.value == null && !grabbedScrollbar) holdingPlayhead = true
}

function mouseDown(event: MouseEvent) {
  if (!canvas.value) return

  if (event.button == 0) {
    mouse = true

    handleSelectingMarker(event)

    handleSelectingScrollbar(event)

    handleSelectingPlayhead(event)
  } else if (event.button == 2) {
    mouseAlt = true
    selectedOriginal.value = XtoFrame(event.clientX)
    selectedStart.value = XtoFrame(event.clientX)
    framesSelected.value = true
  }

  mouseMove(event)
}

async function mouseUp(event: MouseEvent) {
  if (event.button == 0) {
    grabbedScrollbar = false

    if (heldMarker.value != null) {
      const droppedFrame = XtoFrame(heldMarkerX.value)

      const marker = EngineStore.markers.find(
        (marker: any) => marker.id == heldMarker.value
      )

      if (!marker) return

      if (marker.frame != droppedFrame)
        EditorStore.updateMarker(heldMarker.value, marker.name, droppedFrame)

      heldMarker.value = null
    } else if (mouse) {
      EditorStore.pause()

      await EngineStore.setFrame(holdingPlayheadFrame.value)

      holdingPlayhead = false
    }

    mouse = false
  } else if (event.button == 2) {
    if (mouseAlt && selectedEnd.value == selectedStart.value) {
      framesSelected.value = false
    }
    mouseAlt = false
  }
}

function handleMovePlayhead(event: MouseEvent) {
  if (!mouse) return
  if (grabbedScrollbar) return
  if (!holdingPlayhead) return

  holdingPlayheadFrame.value = Math.min(
    Math.max(XtoFrame(event.clientX), 0),
    EngineStore.length - 1
  )
}

function handleMoveMarker(event: MouseEvent) {
  if (!mouse) return
  if (grabbedScrollbar) return
  if (heldMarker.value == null) return

  heldMarkerX.value = Math.min(
    Math.max(
      event.clientX + heldMarkerOffset,
      frameToRelativeX(0) / canvasScale
    ),
    frameToRelativeX(EngineStore.length - 1) / canvasScale
  )
}

function handleMoveScrollbar(event: MouseEvent) {
  if (!canvas.value) return
  if (!mouse) return
  if (!grabbedScrollbar) return

  const relativeX = event.clientX - canvas.value.getBoundingClientRect().left

  const newScrollbarPosition = relativeX + grabbedScrollbarOffset
  const newScrollBarFrame =
    (newScrollbarPosition / (canvas.value.width / canvasScale)) *
    EngineStore.length

  const viewRange = endFrame.value - startFrame.value
  startFrame.value = newScrollBarFrame
  endFrame.value = newScrollBarFrame + viewRange
}

function handleMoveSelect(event: MouseEvent) {
  if (mouse) return
  if (!mouseAlt) return

  const frame = XtoFrame(event.clientX)

  if (frame < selectedOriginal.value) {
    selectedEnd.value = selectedOriginal.value
    selectedStart.value = frame
  } else {
    selectedStart.value = selectedOriginal.value
    selectedEnd.value = frame
  }
}

function handleMarkerHighlight(event: MouseEvent) {
  if (!canvas.value) return
  if (mouse) return
  if (mouseAlt) return

  highlightedMarker.value = null

  const relativeY = event.clientY - canvas.value.getBoundingClientRect().top

  if (relativeY < 58) return
  if (relativeY > 72) return

  const ctx = canvas.value.getContext('2d')!

  for (const marker of EngineStore.markers) {
    if (event.clientX < frameToRelativeX(marker.frame) / canvasScale) continue

    ctx.font = '10px JetBrainsMono'

    const width = ctx.measureText(marker.name).width + 8

    if (event.clientX > frameToRelativeX(marker.frame) / canvasScale + width)
      continue

    highlightedMarker.value = marker.id
  }
}

async function mouseMove(event: MouseEvent) {
  handleMovePlayhead(event)
  handleMoveMarker(event)
  handleMoveScrollbar(event)
  handleMoveSelect(event)
  handleMarkerHighlight(event)
}

function loop() {
  EditorStore.looping = !EditorStore.looping

  if (!EditorStore.looping) return

  if (!framesSelected || selectedStart == selectedEnd) {
    EditorStore.looping = false

    return
  }

  EditorStore.loopingStart = selectedStart.value
  EditorStore.loopingEnd = selectedEnd.value
}

let startFrame = ref(-5)
let endFrame = ref(EngineStore.length + 5)

// watch(
//   () => EngineStore.length,
//   () => {
//     startFrame.value = -5
//     endFrame.value = EngineStore.length - 1 + 5
//   }
// )

function scroll(event: any) {
  const scrollX = event.deltaX / 1000
  const scrollY = event.deltaY / 10000

  let viewRange = endFrame.value - startFrame.value

  if (scrollY != 0) {
    let zoom = Math.pow(Math.pow(viewRange, 1 / 10) + scrollY, 10)
    zoom = Math.max(zoom, 1)

    const mid = startFrame.value + (endFrame.value - startFrame.value) / 2

    startFrame.value = mid - zoom / 2
    endFrame.value = mid + zoom / 2
  }

  if (scrollX != 0) {
    viewRange = endFrame.value - startFrame.value

    startFrame.value += viewRange * scrollX
    endFrame.value += viewRange * scrollX
  }
}

watch(startFrame, () => render())
watch(endFrame, () => render())
watch(holdingPlayheadFrame, () => render())

const secondaryColor = '#242424'
const grabColor = '#32a6fc'
const alternateGrab = '#17222b'
const textColor = '#d9d9d9'
const alternateTextColor = '#a7a7a7'

function render() {
  if (!canvas.value) return
  const ctx = canvas.value.getContext('2d')!
  ctx.clearRect(0, 0, canvas.value.width, canvas.value.height)

  // Seperator Bar
  ctx.strokeStyle = secondaryColor
  ctx.lineWidth = 1 * canvasScale
  ctx.beginPath()
  ctx.moveTo(0, 32 * canvasScale)
  ctx.lineTo(canvas.value.width, 32 * canvasScale)
  ctx.stroke()
  const labelInterval = Math.max(
    Math.floor(
      (Math.ceil(endFrame.value) - Math.floor(startFrame.value)) / 60
    ) * 5,
    1
  )
  const lineInterval = Math.max(
    Math.floor((Math.ceil(endFrame.value) - Math.floor(startFrame.value)) / 60),
    1
  )

  for (
    let frame =
      Math.floor(Math.floor(startFrame.value) / lineInterval) * lineInterval;
    frame < Math.ceil(endFrame.value);
    frame += lineInterval
  ) {
    const x = frameToRelativeX(frame)
    // Frame bar
    ctx.strokeStyle = alternateTextColor
    ctx.lineWidth = 1 * canvasScale
    ctx.beginPath()
    ctx.moveTo(x, (frame % labelInterval == 0 ? 16 : 24) * canvasScale)
    ctx.lineTo(x, 32 * canvasScale)
    ctx.stroke()

    if (frame % labelInterval != 0) continue

    // Frame numbers
    ctx.fillStyle = alternateTextColor
    ctx.font = `${10 * canvasScale}px JetBrainsMono`
    ctx.fillText(frame.toString(), x + 4 * canvasScale, 24 * canvasScale)
  }

  // Volume
  for (
    let frame = Math.floor(startFrame.value);
    frame < Math.ceil(endFrame.value);
    frame++
  ) {
    // Frame bar
    ctx.fillStyle = 'rgba(255, 255, 255, 0.1)'

    const size =
      (EditorStore.audioInference[frame] || 0) *
      ((canvas.value.height - 72 * canvasScale) / 2)

    ctx.fillRect(
      frameToRelativeX(frame),
      (canvas.value.height - 72 * canvasScale) / 2 -
        size / 2 +
        72 * canvasScale,
      frameToRelativeX(frame + 1) - frameToRelativeX(frame),
      size
    )
  }

  // Scenes
  for (
    let sceneIndex = 0;
    sceneIndex < EditorStore.sceneInference.length;
    sceneIndex++
  ) {
    const scene = EditorStore.sceneInference[sceneIndex]

    ctx.font = `${10 * canvasScale}px JetBrainsMono`

    const textWidth = ctx.measureText(scene.name).width + 8 * canvasScale

    const frameWidth = EditorStore.sceneInference[sceneIndex + 1]
      ? frameToRelativeX(EditorStore.sceneInference[sceneIndex + 1].frame) -
        frameToRelativeX(scene.frame)
      : frameToRelativeX(EngineStore.length) - frameToRelativeX(scene.frame)

    ctx.fillStyle = secondaryColor
    ctx.beginPath()
    roundRect(
      frameToRelativeX(scene.frame),
      38 * canvasScale,
      Math.max(0, frameWidth - 4 * canvasScale),
      16 * canvasScale,
      [0, 6 * canvasScale, 6 * canvasScale, 6 * canvasScale]
    )
    ctx.fill()

    if (textWidth > frameWidth) continue

    ctx.fillStyle = textColor
    ctx.fillText(
      scene.name,
      frameToRelativeX(scene.frame) + 4 * canvasScale,
      42 * canvasScale + ctx.measureText(scene.name).actualBoundingBoxAscent
    )
  }

  function roundRect(
    x: number,
    y: number,
    width: number,
    height: number,
    radius: number[]
  ) {
    ctx.moveTo(x + radius[0], y)
    ctx.lineTo(x + width - radius[3], y)
    ctx.quadraticCurveTo(x + width, y, x + width, y + radius[3])
    ctx.lineTo(x + width, y + height - radius[2])
    ctx.quadraticCurveTo(
      x + width,
      y + height,
      x + width - radius[2],
      y + height
    )
    ctx.lineTo(x + radius[1], y + height)
    ctx.quadraticCurveTo(x, y + height, x, y + height - radius[1])
    ctx.lineTo(x, y + radius[0])
    ctx.quadraticCurveTo(x, y, x + radius[0], y)
    ctx.closePath()
  }

  // Markers
  for (const marker of EngineStore.markers) {
    if (marker.id == heldMarker.value) continue

    ctx.font = `${10 * canvasScale}px JetBrainsMono`

    const width = ctx.measureText(marker.name).width + 8 * canvasScale

    if (
      (highlightedMarker.value == marker.id && heldMarker.value == null) ||
      EditorStore.selectedMarker == marker.id
    ) {
      ctx.strokeStyle = textColor
      ctx.lineWidth = 1 * canvasScale
    }

    ctx.fillStyle = alternateGrab
    ctx.beginPath()
    roundRect(
      frameToRelativeX(marker.frame),
      58 * canvasScale,
      width,
      16 * canvasScale,
      [
        0,
        (16 * canvasScale) / 2,
        (16 * canvasScale) / 2,
        (16 * canvasScale) / 2,
      ]
    )
    ctx.fill()

    if (
      (highlightedMarker.value == marker.id && heldMarker.value == null) ||
      EditorStore.selectedMarker == marker.id
    )
      ctx.stroke()

    ctx.fillStyle = textColor
    ctx.fillText(
      marker.name,
      frameToRelativeX(marker.frame) + 4 * canvasScale,
      62 * canvasScale + ctx.measureText(marker.name).actualBoundingBoxAscent
    )
  }

  if (heldMarker.value != null) {
    const marker = EngineStore.markers.find(
      (marker: any) => marker.id == heldMarker.value
    )!

    ctx.font = `${10 * canvasScale}px JetBrainsMono`
    const width = ctx.measureText(marker.name).width + 8 * canvasScale
    ctx.strokeStyle = textColor
    ctx.lineWidth = 1 * canvasScale
    ctx.fillStyle = alternateGrab
    ctx.beginPath()
    roundRect(
      heldMarkerX.value * canvasScale,
      58 * canvasScale,
      width,
      16 * canvasScale,
      [
        0,
        (16 * canvasScale) / 2,
        (16 * canvasScale) / 2,
        (16 * canvasScale) / 2,
      ]
    )
    ctx.fill()
    ctx.stroke()
    ctx.fillStyle = textColor
    ctx.fillText(
      marker.name,
      heldMarkerX.value * canvasScale + 4 * canvasScale,
      62 * canvasScale + ctx.measureText(marker.name).actualBoundingBoxAscent
    )
  }

  // Left Side
  if (startFrame.value < 0) {
    ctx.fillStyle = 'rgba(0, 0, 0, 0.3)'
    ctx.fillRect(0, 0, frameToRelativeX(0), canvas.value.height)
  }

  // Right Side
  if (endFrame.value >= EngineStore.length) {
    ctx.fillStyle = 'rgba(0, 0, 0, 0.3)'
    ctx.fillRect(
      frameToRelativeX(EngineStore.length),
      0,
      frameToRelativeX(endFrame.value) - frameToRelativeX(EngineStore.length),
      canvas.value.height
    )
  }

  // Selected Area
  if (framesSelected.value) {
    ctx.fillStyle = 'rgba(255, 255, 255, 0.1)'
    ctx.fillRect(
      frameToRelativeX(selectedStart.value),
      0,
      frameToRelativeX(selectedEnd.value) -
        frameToRelativeX(selectedStart.value),
      canvas.value.height
    )
  }

  // Looping Area
  if (EditorStore.looping) {
    ctx.fillStyle = 'rgba(50, 166, 252, 0.3)'
    ctx.fillRect(
      frameToRelativeX(EditorStore.loopingStart),
      0,
      frameToRelativeX(EditorStore.loopingEnd) -
        frameToRelativeX(EditorStore.loopingStart),
      canvas.value.height
    )
  }

  // Playhead
  ctx.strokeStyle = grabColor
  ctx.lineWidth = 1 * canvasScale
  ctx.beginPath()
  ctx.moveTo(
    frameToRelativeX(
      holdingPlayhead ? holdingPlayheadFrame.value : EngineStore.frame
    ),
    0
  )
  ctx.lineTo(
    frameToRelativeX(
      holdingPlayhead ? holdingPlayheadFrame.value : EngineStore.frame
    ),
    canvas.value.height
  )
  ctx.stroke()

  // Scrollbar
  ctx.fillStyle = 'rgba(0, 0, 0, 0.1)'
  ctx.fillRect(0, canvas.value.height, canvas.value.width, -8 * canvasScale)
  ctx.fillStyle = '#242424'
  ctx.fillRect(
    Math.floor((canvas.value.width * startFrame.value) / EngineStore.length),
    canvas.value.height,
    Math.floor(
      (canvas.value.width * (endFrame.value - startFrame.value)) /
        EngineStore.length
    ),
    -8 * canvasScale
  )
}

watch(() => EngineStore.frame, render)

watch(() => EngineStore.updatedDataEvent, render)

watch(() => EditorStore.audioInference, render)

watch(() => EditorStore.sceneInference, render)

watch(framesSelected, render)

watch(selectedStart, render)

watch(selectedEnd, render)

watch(() => EditorStore.looping, render)

watch(() => EditorStore.loopingStart, render)

watch(() => EditorStore.loopingEnd, render)

watch(highlightedMarker, render)

watch(heldMarker, render)

watch(heldMarkerX, render)

const canvas: Ref<null | HTMLCanvasElement> = ref(null)
const canvasWrapper: Ref<null | HTMLDivElement> = ref(null)

function fixCanvasSize() {
  if (!canvasWrapper.value) return
  if (!canvas.value) return

  canvas.value.width = canvasWrapper.value.offsetWidth * canvasScale
  canvas.value.height = canvasWrapper.value.offsetHeight * canvasScale
  canvas.value.style.maxWidth = canvasWrapper.value.offsetWidth + 'px'
  canvas.value.style.maxHeight = canvasWrapper.value.offsetHeight + 'px'

  render()
}

onMounted(() => {
  if (!canvasWrapper.value) return

  new ResizeObserver(fixCanvasSize).observe(canvasWrapper.value)

  fixCanvasSize()

  render()
})
</script>

<style scoped>
#speed-input {
  font-size: x-small;
  width: 3rem;
  background: none;
  padding: 0;
}

#component {
  min-height: 18rem;

  border-top: solid 1px var(--secondary);

  display: flex;
  flex-direction: column;
}

#control-bar {
  height: 2rem;

  border-bottom: solid 1px var(--secondary);

  display: flex;
  justify-content: space-between;
  align-items: center;

  box-sizing: border-box;

  padding-left: 0.5rem;
  padding-right: 0.5rem;
}

#canvas-wrapper {
  flex-grow: 1;
}

#canvas {
  display: block;
  position: absolute;
}

.control-bar-group {
  display: flex;
  gap: 0.5rem;
}

#time-input {
  font-size: x-small;
}

#frame-input {
  font-size: x-small;

  color: var(--alternate-text);

  margin-top: auto;
  margin-bottom: auto;
}

#time-input,
#frame-input {
  width: 3rem;
  background: none;
  padding: 0;
}

#frame-length {
  font-size: x-small;

  color: var(--alternate-text);

  margin: 0;

  width: 3rem;

  text-align: right;

  margin-top: auto;
  margin-bottom: auto;
}

#length {
  font-size: x-small;

  margin: 0;

  width: 3rem;

  text-align: right;
}

#redo.looping {
  color: var(--grab);
}
</style>

// editor-new/src/Components/Timeline.svelte
<script lang="ts">
	import { subscribe, tick } from 'svelte/internal'
	import { engine, engineData, frame } from '../Stores/EngineStore'
	import { get } from 'svelte/store'
	import { pause } from '../Stores/PlayStore'
	import { audioInference, markerInference, sceneInference } from '../Stores/InferenceStore'

	let canvas: undefined | HTMLCanvasElement = undefined
	let containerWidth = 1920
	let containerHeight = 1080

	let offset = 0
	let scale = 1

	let mouse = false

	async function mouseDown(event: MouseEvent) {
		mouse = true

		const currentEngine = get(engine)

		const newFrame = Math.max(
			0,
			Math.min(currentEngine.length - 1, Math.round(getFrameAtXPosition(event.clientX)))
		)

		pause()

		await currentEngine.jumpToFrame(newFrame)
		frame.set(newFrame)
	}

	function mouseMove(event: MouseEvent) {
		if (!mouse) return

		pause()

		const newFrame = Math.max(
			0,
			Math.min(get(engine).length - 1, Math.round(getFrameAtXPosition(event.clientX)))
		)

		frame.set(newFrame)
	}

	async function mouseUp(event: MouseEvent) {
		mouse = false

		const currentFrame = get(frame)
		const currentEngine = get(engine)

		if (currentEngine === undefined) return

		await currentEngine.jumpToFrame(currentFrame)
		frame.set(-1)
		frame.set(currentFrame)
	}

	function getFrameAtXPosition(x: number): number {
		return (x - offset) / 5 / scale
	}

	function getXPositionOfFrame(frame: number): number {
		return frame * 5 * scale + offset
	}

	function scroll(event: any) {
		const canvasBounds = canvas.getBoundingClientRect()
		const mouseOffset = event.clientX - canvasBounds.left - getXPositionOfFrame(0)
		const scrollX = event.deltaX / -36
		const scrollY = event.deltaY / -4000

		const zoom = Math.exp(scrollY)

		offset += mouseOffset * (1 - zoom)

		scale *= zoom

		offset += (canvas.width / 25) * scrollX
	}

	const mainColor = '#141414'
	const secondaryColor = '#242424'
	const tertiaryColor = '#1c1c1c'
	const grabColor = '#32a6fc'
	const alternateGrabColor = '#17222b'
	const textColor = '#d9d9d9'
	const alternateTextColor = '#a7a7a7'

	function renderFrameLabels(canvas: HTMLCanvasElement, ctx: CanvasRenderingContext2D) {
		const frameWidth =
			canvas && scale ? getFrameAtXPosition(canvas.width) - getFrameAtXPosition(0) : 0

		const interval = Math.max(
			Math.floor(Math.pow(2, Math.floor(Math.log(frameWidth) / Math.log(2))) / 8),
			1
		)
		const firstLabel = Math.floor(getFrameAtXPosition(0) / interval) * interval

		for (
			let frame = firstLabel;
			frame < Math.ceil(getFrameAtXPosition(canvas.width));
			frame += interval
		) {
			const x = getXPositionOfFrame(frame)

			ctx.fillStyle = alternateTextColor
			ctx.font = `${10}px Mulish`

			const measure = ctx.measureText(frame.toString())

			ctx.fillText(
				frame.toString(),
				x - measure.actualBoundingBoxRight / 2,
				10 + measure.actualBoundingBoxAscent / 2
			)
		}
	}

	function renderFrameLines(canvas: HTMLCanvasElement, ctx: CanvasRenderingContext2D) {
		const frameWidth =
			canvas && scale ? getFrameAtXPosition(canvas.width) - getFrameAtXPosition(0) : 0

		const interval = Math.max(
			Math.floor(Math.pow(2, Math.floor(Math.log(frameWidth) / Math.log(2))) / 8),
			1
		)
		const firstLabel = Math.floor(getFrameAtXPosition(0) / interval) * interval

		for (
			let frame = firstLabel;
			frame < Math.ceil(getFrameAtXPosition(canvas.width));
			frame += interval
		) {
			const x = getXPositionOfFrame(frame)

			ctx.fillStyle = secondaryColor
			ctx.fillRect(x, 20, 1, canvas.height - 20)
		}
	}

	function renderAudio(canvas: HTMLCanvasElement, ctx: CanvasRenderingContext2D) {
		const currentAudioInference = get(audioInference)

		for (
			let frame = Math.floor(getFrameAtXPosition(0));
			frame < Math.ceil(getFrameAtXPosition(canvas.width));
			frame++
		) {
			if (frame < 0 || frame >= get(engine).length) continue

			const x = getXPositionOfFrame(frame)

			ctx.fillStyle = secondaryColor
			ctx.fillRect(
				x,
				canvas.height,
				getXPositionOfFrame(frame + 1) - getXPositionOfFrame(frame),
				-100 * currentAudioInference[frame]
			)
		}
	}

	function renderPlayhead(canvas: HTMLCanvasElement, ctx: CanvasRenderingContext2D) {
		ctx.fillStyle = grabColor
		ctx.fillRect(getXPositionOfFrame(get(frame)), 0, 1, canvas.height)
	}

	function renderValidArea(canvas: HTMLCanvasElement, ctx: CanvasRenderingContext2D) {
		ctx.fillStyle = tertiaryColor
		ctx.fillRect(
			getXPositionOfFrame(0),
			0,
			getXPositionOfFrame(get(engine).length - 1) - getXPositionOfFrame(0),
			canvas.height
		)
	}

	async function render() {
		if (!canvas) return
		if (get(engine) === undefined) return

		const ctx = canvas.getContext('2d')!
		ctx.imageSmoothingEnabled = false

		ctx.clearRect(0, 0, canvas.width, canvas.height)

		renderValidArea(canvas, ctx)
		renderFrameLabels(canvas, ctx)
		renderFrameLines(canvas, ctx)
		renderAudio(canvas, ctx)
		renderPlayhead(canvas, ctx)
	}

	subscribe(engine, value => {
		if (value === undefined) return

		scale = 1
		offset = 0

		const frameWidth =
			canvas && scale ? getFrameAtXPosition(canvas.width) - getFrameAtXPosition(0) : 0

		scale = frameWidth / (value.length - 1) / 1.5
		offset = canvas.width / 1.5 / 4
	})

	subscribe(frame, () => {
		render()
	})

	subscribe(audioInference, () => {
		render()
	})

	$: containerWidth, containerHeight, tick().then(render)
	$: scale, offset, render()
</script>

<main
	bind:clientWidth={containerWidth}
	bind:clientHeight={containerHeight}
	on:mousedown={mouseDown}
	on:mousemove={mouseMove}
	on:mouseleave={mouseUp}
	on:mouseup={mouseUp}
	on:wheel={scroll}
>
	<canvas bind:this={canvas} width={containerWidth} height={containerHeight} />

	{#if $engineData}
		{#each $sceneInference as scene}
			<p
				class="scene"
				style="left: {scene.frame * 5 * scale + offset}px; width:calc({scene.length *
					5 *
					scale}px - 0.4rem)"
			>
				{scene.name}
			</p>
		{/each}

		{#each $markerInference as marker}
			<div
				class="marker-length"
				style="left: {marker.frame * 5 * scale + offset}px; width:calc({marker.length *
					5 *
					scale}px + 0.4rem)"
			/>
			<p class="marker" style="left: {(marker.frame + marker.length) * 5 * scale + offset}px">
				{marker.name}
			</p>
		{/each}
	{/if}
</main>

<style>
	main {
		background: #000000;
		max-height: 50%;
		height: 50%;

		display: flex;
		justify-content: center;
		align-items: center;

		overflow: hidden;

		position: relative;
	}

	canvas {
		background: var(--main);
		image-rendering: pixelated;

		display: block;

		width: 100%;
		height: 100%;
	}

	.marker-length {
		background-color: var(--secondary);

		border-radius: 0.2rem;

		position: absolute;
		top: 52px;

		height: 1.3rem;
	}

	.marker {
		background-color: var(--grab);

		border-radius: 0.4rem;
		border-top-left-radius: 0;

		margin: 0;

		padding: 0.2rem;
		font-size: 0.7rem;

		display: table;

		position: absolute;
		top: 52px;

		z-index: 1;
	}

	.scene {
		background-color: var(--secondary);

		border-radius: 0.2rem;

		margin: 0;

		padding: 0.2rem;
		font-size: 0.7rem;

		position: absolute;
		top: 24px;

		color: var(--alternate-text);
	}
</style>
