// editor-new/src/Components/Timeline.svelte
<script lang="ts">
	import { subscribe, tick } from 'svelte/internal'
	import { engine, engineData, frame } from '../Stores/EngineStore'
	import { get } from 'svelte/store'
	import { pause } from '../Stores/PlayStore'
	import { audioInference, markerInference, sceneInference } from '../Stores/InferenceStore'

	let canvas: undefined | HTMLCanvasElement = undefined
	let containerWidth = 1920
	let containerHeight = 1080

	let offset = 0
	let scale = 1

	let mouse = false

	async function mouseDown(event: MouseEvent) {
		mouse = true

		const currentEngine = get(engine)

		const newFrame = Math.max(
			0,
			Math.min(currentEngine.length - 1, Math.round(getFrameAtXPosition(event.clientX)))
		)

		pause()

		await currentEngine.jumpToFrame(newFrame)
		frame.set(newFrame)
	}

	function mouseMove(event: MouseEvent) {
		if (!mouse) return

		pause()

		const newFrame = Math.max(
			0,
			Math.min(get(engine).length - 1, Math.round(getFrameAtXPosition(event.clientX)))
		)

		frame.set(newFrame)
	}

	async function mouseUp(event: MouseEvent) {
		mouse = false

		const currentFrame = get(frame)
		const currentEngine = get(engine)

		if (currentEngine === undefined) return

		await currentEngine.jumpToFrame(currentFrame)
		frame.set(-1)
		frame.set(currentFrame)
	}

	function getFrameAtXPosition(x: number): number {
		return (x - offset) / 5 / scale
	}

	function getXPositionOfFrame(frame: number): number {
		return frame * 5 * scale + offset
	}

	function scroll(event: any) {
		const canvasBounds = canvas.getBoundingClientRect()
		const mouseOffset = event.clientX - canvasBounds.left - getXPositionOfFrame(0)
		const scrollX = event.deltaX / -36
		const scrollY = event.deltaY / -4000

		const zoom = Math.exp(scrollY)

		offset += mouseOffset * (1 - zoom)

		scale *= zoom

		offset += (canvas.width / 25) * scrollX
	}

	const mainColor = '#141414'
	const secondaryColor = '#242424'
	const tertiaryColor = '#1c1c1c'
	const grabColor = '#32a6fc'
	const alternateGrabColor = '#17222b'
	const textColor = '#d9d9d9'
	const alternateTextColor = '#a7a7a7'

	function renderFrameLabels(canvas: HTMLCanvasElement, ctx: CanvasRenderingContext2D) {
		const frameWidth =
			canvas && scale ? getFrameAtXPosition(canvas.width) - getFrameAtXPosition(0) : 0

		const interval = Math.max(
			Math.floor(Math.pow(2, Math.floor(Math.log(frameWidth) / Math.log(2))) / 8),
			1
		)
		const firstLabel = Math.floor(getFrameAtXPosition(0) / interval) * interval

		for (
			let frame = firstLabel;
			frame < Math.ceil(getFrameAtXPosition(canvas.width));
			frame += interval
		) {
			const x = getXPositionOfFrame(frame)

			ctx.fillStyle = alternateTextColor
			ctx.font = `${10}px Mulish`

			const measure = ctx.measureText(frame.toString())

			ctx.fillText(
				frame.toString(),
				x - measure.actualBoundingBoxRight / 2,
				10 + measure.actualBoundingBoxAscent / 2
			)
		}
	}

	function renderFrameLines(canvas: HTMLCanvasElement, ctx: CanvasRenderingContext2D) {
		const frameWidth =
			canvas && scale ? getFrameAtXPosition(canvas.width) - getFrameAtXPosition(0) : 0

		const interval = Math.max(
			Math.floor(Math.pow(2, Math.floor(Math.log(frameWidth) / Math.log(2))) / 8),
			1
		)
		const firstLabel = Math.floor(getFrameAtXPosition(0) / interval) * interval

		for (
			let frame = firstLabel;
			frame < Math.ceil(getFrameAtXPosition(canvas.width));
			frame += interval
		) {
			const x = getXPositionOfFrame(frame)

			ctx.fillStyle = secondaryColor
			ctx.fillRect(x, 20, 1, canvas.height - 20)
		}
	}

	function renderAudio(canvas: HTMLCanvasElement, ctx: CanvasRenderingContext2D) {
		const currentAudioInference = get(audioInference)

		for (
			let frame = Math.floor(getFrameAtXPosition(0));
			frame < Math.ceil(getFrameAtXPosition(canvas.width));
			frame++
		) {
			if (frame < 0 || frame >= get(engine).length) continue

			const x = getXPositionOfFrame(frame)

			ctx.fillStyle = secondaryColor
			ctx.fillRect(
				x,
				canvas.height,
				getXPositionOfFrame(frame + 1) - getXPositionOfFrame(frame),
				-100 * currentAudioInference[frame]
			)
		}
	}

	function renderPlayhead(canvas: HTMLCanvasElement, ctx: CanvasRenderingContext2D) {
		ctx.fillStyle = grabColor
		ctx.fillRect(getXPositionOfFrame(get(frame)), 0, 1, canvas.height)
	}

	function renderValidArea(canvas: HTMLCanvasElement, ctx: CanvasRenderingContext2D) {
		ctx.fillStyle = tertiaryColor
		ctx.fillRect(
			getXPositionOfFrame(0),
			0,
			getXPositionOfFrame(get(engine).length - 1) - getXPositionOfFrame(0),
			canvas.height
		)
	}

	async function render() {
		if (!canvas) return
		if (get(engine) === undefined) return

		const ctx = canvas.getContext('2d')!
		ctx.imageSmoothingEnabled = false

		ctx.clearRect(0, 0, canvas.width, canvas.height)

		renderValidArea(canvas, ctx)
		renderFrameLabels(canvas, ctx)
		renderFrameLines(canvas, ctx)
		renderAudio(canvas, ctx)
		renderPlayhead(canvas, ctx)
	}

	subscribe(engine, value => {
		if (value === undefined) return

		scale = 1
		offset = 0

		const frameWidth =
			canvas && scale ? getFrameAtXPosition(canvas.width) - getFrameAtXPosition(0) : 0

		scale = frameWidth / (value.length - 1) / 1.5
		offset = canvas.width / 1.5 / 4
	})

	subscribe(frame, () => {
		render()
	})

	subscribe(audioInference, () => {
		render()
	})

	$: containerWidth, containerHeight, tick().then(render)
	$: scale, offset, render()
</script>

<main
	bind:clientWidth={containerWidth}
	bind:clientHeight={containerHeight}
	on:mousedown={mouseDown}
	on:mousemove={mouseMove}
	on:mouseleave={mouseUp}
	on:mouseup={mouseUp}
	on:wheel={scroll}
>
	<canvas bind:this={canvas} width={containerWidth} height={containerHeight} />

	{#if $engineData}
		{#each $sceneInference as scene}
			<p
				class="scene"
				style="left: {scene.frame * 5 * scale + offset}px; width:calc({scene.length *
					5 *
					scale}px - 0.4rem)"
			>
				{scene.name}
			</p>
		{/each}

		{#each $markerInference as marker}
			<div
				class="marker-length"
				style="left: {marker.frame * 5 * scale + offset}px; width:calc({marker.length *
					5 *
					scale}px + 0.4rem)"
			/>
			<p class="marker" style="left: {(marker.frame + marker.length) * 5 * scale + offset}px">
				{marker.name}
			</p>
		{/each}
	{/if}
</main>

<style>
	main {
		background: #000000;
		max-height: 50%;
		height: 50%;

		display: flex;
		justify-content: center;
		align-items: center;

		overflow: hidden;

		position: relative;
	}

	canvas {
		background: var(--main);
		image-rendering: pixelated;

		display: block;

		width: 100%;
		height: 100%;
	}

	.marker-length {
		background-color: var(--secondary);

		border-radius: 0.2rem;

		position: absolute;
		top: 52px;

		height: 1.3rem;
	}

	.marker {
		background-color: var(--grab);

		border-radius: 0.4rem;
		border-top-left-radius: 0;

		margin: 0;

		padding: 0.2rem;
		font-size: 0.7rem;

		display: table;

		position: absolute;
		top: 52px;

		z-index: 1;
	}

	.scene {
		background-color: var(--secondary);

		border-radius: 0.2rem;

		margin: 0;

		padding: 0.2rem;
		font-size: 0.7rem;

		position: absolute;
		top: 24px;

		color: var(--alternate-text);
	}
</style>

// src/components/workspace/Timeline.vue
<template>
  <div id="component">
    <div id="control-bar">
      <div class="control-bar-group">
        <input value="0:00" id="time-input" />
        <input value="[0]" id="frame-input" />
      </div>

      <div class="control-bar-group">
        <span class="material-symbols-outlined icon-button"> volume_up </span>

        <span class="material-symbols-outlined icon-button"> fast_rewind </span>
      </div>

      <div class="control-bar-group">
        <span class="material-symbols-outlined icon-button">
          skip_previous
        </span>

        <span
          class="material-symbols-outlined icon-button"
          @click="() => (playing ? pause() : play())"
        >
          {{ playing ? 'pause' : 'play_arrow' }}
        </span>

        <span class="material-symbols-outlined icon-button"> skip_next </span>
      </div>

      <div class="control-bar-group">
        <span class="material-symbols-outlined icon-button"> redo </span>
      </div>

      <div class="control-bar-group">
        <p id="frame-length">[60]</p>
        <p id="length">0:01</p>
      </div>
    </div>
    <div ref="canvasWrapper" id="canvas-wrapper">
      <canvas
        ref="canvas"
        id="canvas"
        @mousedown="mouseDown"
        @mouseup="() => (mouse = false)"
        @mouseleave="() => (mouse = false)"
        @mousemove="mouseMove"
        @wheel="scroll"
      ></canvas>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, Ref, ref, watch } from 'vue'

import { useWorkspaceStore } from '@/stores/WorkspaceStore'

const WorkspaceStore = useWorkspaceStore()

let playing = ref(false)
let startedPlayingTime = 0
let startedFrame = 0

async function playUpdate() {
  if (!playing.value) return

  const now = Date.now()

  const newFrame =
    Math.floor(((now - startedPlayingTime) / 1000) * WorkspaceStore.frameRate) +
    startedFrame

  await WorkspaceStore.updateFrame(newFrame)

  requestAnimationFrame(playUpdate)
}

function play() {
  playing.value = true
  startedPlayingTime = Date.now()
  startedFrame = WorkspaceStore.frame

  requestAnimationFrame(playUpdate)
}

function pause() {
  playing.value = false
}

let mouse = false

function mouseDown(event: MouseEvent) {
  mouse = true

  mouseMove(event)
}

async function mouseMove(event: MouseEvent) {
  if (!mouse) return
  if (!canvas.value) return

  const factor =
    (event.clientX - canvas.value.getBoundingClientRect().left) /
    canvas.value.width

  await WorkspaceStore.updateFrame(
    Math.floor(factor * (endFrame.value - startFrame.value) + startFrame.value)
  )
}

let startFrame = ref(0)
let endFrame = ref(60)

watch(
  () => WorkspaceStore.loaded,
  () => (endFrame.value = WorkspaceStore.length)
)

function scroll(event: any) {
  const scrollX = Math.ceil(event.deltaX / 100)
  const scrollY = Math.ceil(event.deltaY / 100)

  let viewRange = endFrame.value - startFrame.value

  if (scrollY != 0) {
    let zoomAmount =
      (Math.ceil(
        Math.abs(Math.pow(Math.log(viewRange / 60), Math.abs(scrollY)))
      ) *
        scrollY) /
      Math.abs(scrollY)

    if (zoomAmount == 0) zoomAmount = 1 * (scrollY / Math.abs(scrollY))

    const midPoint = Math.floor(
      startFrame.value + (endFrame.value - startFrame.value) / 2
    )

    startFrame.value = startFrame.value - zoomAmount
    endFrame.value = endFrame.value + zoomAmount

    if (endFrame.value - startFrame.value <= 1) {
      startFrame.value = midPoint
      endFrame.value = midPoint + 1
    }
  }

  if (scrollX != 0) {
    viewRange = endFrame.value - startFrame.value

    startFrame.value += Math.ceil((scrollX * viewRange) / 10)
    endFrame.value += Math.ceil((scrollX * viewRange) / 10)

    startFrame.value = Math.min(
      Math.max(startFrame.value, 0),
      endFrame.value - 1
    )
    endFrame.value = Math.min(
      Math.max(endFrame.value, startFrame.value + 1),
      WorkspaceStore.length
    )

    if (startFrame.value == 0) endFrame.value = viewRange
    if (endFrame.value == WorkspaceStore.length)
      startFrame.value = endFrame.value - viewRange
  }

  startFrame.value = Math.min(Math.max(startFrame.value, 0), endFrame.value - 1)
  endFrame.value = Math.min(
    Math.max(endFrame.value, startFrame.value + 1),
    WorkspaceStore.length
  )
}

watch(startFrame, () => render())
watch(endFrame, () => render())

const secondaryColor = '#242424'
const grabColor = '#32a6fc'
const alternateTextColor = '#a7a7a7'

function frameToRelativeX(frame: number): number {
  if (!canvas.value) return -1

  return Math.floor(
    ((frame - startFrame.value) / (endFrame.value - startFrame.value)) *
      canvas.value.width
  )
}

function render() {
  if (!canvas.value) return

  const ctx = canvas.value.getContext('2d')!

  ctx.clearRect(0, 0, canvas.value.width, canvas.value.height)

  // Seperator Bar
  ctx.strokeStyle = secondaryColor
  ctx.lineWidth = 1
  ctx.beginPath()
  ctx.moveTo(0.5, 32.5)
  ctx.lineTo(canvas.value.width, 32)
  ctx.stroke()

  const labelInterval = Math.max(
    Math.floor((endFrame.value - startFrame.value) / 60) * 5,
    1
  )
  const lineInterval = Math.max(
    Math.floor((endFrame.value - startFrame.value) / 60),
    1
  )

  for (let frame = startFrame.value; frame < endFrame.value; frame++) {
    if (frame % lineInterval != 0) continue

    const x = Math.floor(
      ((frame - startFrame.value) / (endFrame.value - startFrame.value)) *
        canvas.value.width
    )

    // Frame bar
    ctx.strokeStyle = alternateTextColor
    ctx.lineWidth = 1
    ctx.beginPath()
    ctx.moveTo(x, frame % labelInterval == 0 ? 16 : 24)
    ctx.lineTo(x, 32)
    ctx.stroke()

    if (frame % labelInterval != 0) continue

    // Frame numbers
    ctx.fillStyle = alternateTextColor
    ctx.font = '10px JetBrainsMono'
    ctx.fillText(frame.toString(), x + 4, 24)
  }

  // Playhead
  ctx.strokeStyle = grabColor
  ctx.lineWidth = 1
  ctx.beginPath()
  ctx.moveTo(frameToRelativeX(WorkspaceStore.frame), 0)
  ctx.lineTo(frameToRelativeX(WorkspaceStore.frame), canvas.value.height)
  ctx.stroke()
}

watch(
  () => WorkspaceStore.frame,
  () => {
    render()
  }
)

const canvas: Ref<null | HTMLCanvasElement> = ref(null)
const canvasWrapper: Ref<null | HTMLDivElement> = ref(null)

function fixCanvasSize() {
  if (!canvasWrapper.value) return
  if (!canvas.value) return

  canvas.value.width = canvasWrapper.value.offsetWidth
  canvas.value.height = canvasWrapper.value.offsetHeight

  render()
}

onMounted(() => {
  if (!canvasWrapper.value) return

  new ResizeObserver(fixCanvasSize).observe(canvasWrapper.value)

  fixCanvasSize()

  render()

  if (WorkspaceStore.loaded) endFrame.value = WorkspaceStore.length
})
</script>

<style scoped>
#component {
  min-height: 18rem;

  border-top: solid 1px var(--secondary);

  display: flex;
  flex-direction: column;
}

#control-bar {
  height: 2rem;

  border-bottom: solid 1px var(--secondary);

  display: flex;
  justify-content: space-between;
  align-items: center;

  box-sizing: border-box;

  padding-left: 0.5rem;
  padding-right: 0.5rem;
}

#canvas-wrapper {
  flex-grow: 1;
}

#canvas {
  display: block;
  position: absolute;
}

.control-bar-group {
  display: flex;
  gap: 0.5rem;
}

#time-input {
  font-size: small;
}

#frame-input {
  font-size: 0.7rem;

  color: var(--alternate-text);

  margin-top: auto;
  margin-bottom: auto;
}

#time-input,
#frame-input {
  width: 3rem;
  background: none;
  padding: 0;
}

#frame-length {
  font-size: 0.7rem;

  color: var(--alternate-text);

  margin: 0;

  width: 3rem;

  text-align: right;

  margin-top: auto;
  margin-bottom: auto;
}

#length {
  font-size: small;

  margin: 0;

  width: 3rem;

  text-align: right;
}
</style>
