// src/App.vue
<script setup lang="ts">
// This starter template is using Vue 3 <script setup> SFCs
// Check out https://vuejs.org/api/sfc-script-setup.html#script-setup
import { onMounted, ref } from 'vue'
import Greet from './components/Greet.vue'
import { invoke } from '@tauri-apps/api'

let imageSrc = ref('')

onMounted(async () => {
	const data = (await invoke('preview')) as number[]

	const arrayBuffer = new Uint8Array(data)
	const blob = new Blob([arrayBuffer], { type: 'image/png' })
	const src = window.URL.createObjectURL(blob)

	imageSrc.value = src
})
</script>

<template>
	<div class="container">
		<h1>Welcome to Tauri!</h1>

		<div class="row">
			<a href="https://vitejs.dev" target="_blank">
				<img src="/vite.svg" class="logo vite" alt="Vite logo" />
			</a>
			<a href="https://tauri.app" target="_blank">
				<img src="/tauri.svg" class="logo tauri" alt="Tauri logo" />
			</a>
			<a href="https://vuejs.org/" target="_blank">
				<img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
			</a>
		</div>

		<p>Click on the Tauri, Vite, and Vue logos to learn more.</p>

		<p>
			Recommended IDE setup:
			<a href="https://code.visualstudio.com/" target="_blank">VS Code</a>
			+
			<a href="https://github.com/johnsoncodehk/volar" target="_blank">Volar</a>
			+
			<a href="https://github.com/tauri-apps/tauri-vscode" target="_blank">Tauri</a>
			+
			<a href="https://github.com/rust-lang/rust-analyzer" target="_blank">rust-analyzer</a>
		</p>

		<img id="preview" :src="imageSrc" />

		<Greet />
	</div>
</template>

<style scoped>
.logo.vite:hover {
	filter: drop-shadow(0 0 2em #747bff);
}

.logo.vue:hover {
	filter: drop-shadow(0 0 2em #249b73);
}

#preview {
	width: 512px;
	height: 512px;
}
</style>

// packages/editor/src/App.svelte
<script lang="ts">
	import { onMount } from 'svelte'
	import svelteLogo from './assets/svelte.svg'
	import viteLogo from './assets/vite.svg'
	import Counter from './components/Counter.svelte'
</script>

<main>
	<div>
		<a href="https://vitejs.dev" target="_blank" rel="noreferrer">
			<img src={viteLogo} class="logo" alt="Vite Logo" />
		</a>
		<a href="https://svelte.dev" target="_blank" rel="noreferrer">
			<img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
		</a>
	</div>
	<h1>Vite + Svelte</h1>

	<div class="card">
		<Counter />
	</div>

	<p>
		Check out <a href="https://github.com/sveltejs/kit#readme" target="_blank" rel="noreferrer"
			>SvelteKit</a
		>, the official Svelte app framework powered by Vite!
	</p>

	<p class="read-the-docs">Click on the Vite and Svelte logos to learn more</p>
</main>

<style>
	.logo {
		height: 6em;
		padding: 1.5em;
		will-change: filter;
		transition: filter 300ms;
	}
	.logo:hover {
		filter: drop-shadow(0 0 2em #646cffaa);
	}
	.logo.svelte:hover {
		filter: drop-shadow(0 0 2em #ff3e00aa);
	}
	.read-the-docs {
		color: #888;
	}
</style>
